apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cau0oirxt-go 
  janus-idp.io/tekton: cau0oirxt-go
  backstage.io/kubernetes-id: cau0oirxt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cau0oirxt-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml